common/models/Task.php
<?php

namespace common\models;

use common\events\tasks\TaskHaveCreatedEvent;
use common\events\tasks\TaskHaveUpdatedEvent;
use common\events\tasks\TaskStatusHaveChangedEvent;
use common\traits\AssociateLabels;
use common\traits\EventTrait;
use common\traits\FreeRules;
use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;
use yii\db\ActiveRecord;
use common\components\DateUpdater;

class Task extends ActiveRecord
{
    use FreeRules;
    use AssociateLabels;
    use EventTrait;

    const STATUS = [
        'draft' => 'Черновик',
        'moderation' => 'Модерация',
        'reject' => 'Отклонена',
        'published' => 'Опубликовано',
        'finished' => 'Закрыта',
    ];

    const STATUS_DB = [
        'draft' => 'draft',
        'moderation' => 'moderation',
        'reject' => 'reject',
        'published' => 'published',
        'finished' => 'finished',
    ];

    const TYPE = [
        'quest' => 'Задание',
        'event' => 'Мероприятие',
        'team' => 'Тимбилдинг',
    ];
    const TYPE_DB = [
        'quest' => 'quest',
        'event' => 'event',
        'team' => 'team',
    ];

    const COMPLEXITY = [
        1 => 'Без опыта',
        2 => 'Новичок',
        3 => 'Средний',
        4 => 'Профи',
    ];

    const PRIVILEGE = [
        1 => 'Нет',
        2 => 'Приз',
        3 => 'TU',
    ];

    const PRIVILEGE_DB = [
        'Нет' => 1,
        'Приз' => 2,
        'TU' => 3,
    ];

    const TU_COUNT = [1, 2, 3, 4, 5];

    public function behaviors()
    {
        return [
            [
                'class' => DateUpdater::class,
                'updatedAtAttribute' => 'date_upd',
            ],
            'saveRelations' => [
                'class' => SaveRelationsBehavior::className(),
                'relations' => [
                    'skills',
                    /*          'participants' => [
                                'extraColumns' => function ($model) {
                                  return [
                                    'date_add' => date('Y-m-d H:i:s')
                                  ];
                                }
                              ],*/
                ],
            ],
        ];
    }

    public function fields()
    {
        $parent = parent::fields();

        $parent['d_files'] = function ($model) {
            return $model->files;
        };

        $parent['d_notifies'] = function ($model) {
            return $model->notifies;
        };

        $parent['d_industry'] = function ($model) {
            return $model->industry;
        };

        $parent['d_skills'] = function ($model) {
            return $model->skills;
        };

        return $parent;
    }


    /**
     * ========== RELATIONS =============
     */
    public function getCreator()
    {
        return $this->hasOne(User::class, ['id' => 'uid']);
    }

    public function getProject()
    {
        return $this->hasOne(Project::class, ['id' => 'project_id']);
    }

    public function getSpecialization()
    {
        return $this->hasOne(Specialization::class, ['id' => 'specialization_id']);
    }

    public function getTown()
    {
        return $this->hasOne(Town::class, ['id' => 'town_id']);
    }

    public function getNotifies()
    {
        return $this->hasMany(Notify::class, ['task_id' => 'id']);
    }

    public function getIndustry()
    {
        return $this->hasOne(Industry::class, ['id' => 'industry_id']);
    }

    public function getFiles()
    {
        return $this->hasMany(TaskFile::class, ['task_id' => 'id']);
    }

    public function getFilesSize()
    {
        $res = 0;
        $files = TaskFile::find()->select('size')->where(['task_id' => $this->id])->column();
        if (!empty($files)) {
            foreach ($files as $file) {
                $res += round($file / (1024 * 1024), 3);
            }
        }
        return $res;
    }

    public function getSkills()
    {
        return $this->hasMany(Skill::class, ['id' => 'skill_id'])
            ->viaTable('task_skills', ['task_id' => 'id']);
    }

    public function getParticipants()
    {
        return $this->hasMany(User::class, ['id' => 'participant_id'])
            ->viaTable('task_participant', ['task_id' => 'id']);
    }

    /**
     * ---
     */
    public static function create($uid, $status, $name, $text, $town_id, $type_id, $project_id, $industry_id, $complexity, $specialization_id, $date_end, $points_win, $points_participant, $privilege, $privilege_description, $tu_count, $authored_visible, $is_paid)
    {
        $m = new static();
        $m->uid = $uid;
        $m->status = $status;
        $m->name = $name;
        $m->text = $text;
        $m->town_id = $town_id;
        $m->type_id = $type_id;
        $m->project_id = $project_id;
        $m->industry_id = $industry_id;
        $m->complexity = $complexity;
        $m->specialization_id = $specialization_id;
        $m->date_end = $date_end;
        $m->points_win = $points_win;
        $m->points_participant = $points_participant;
        $m->privilege = $privilege;
        $m->privilege_description = $privilege_description;
        $m->tu_count = $tu_count;
        $m->authored_visible = $authored_visible;
        $m->is_paid = $is_paid;
        $m->recordEvent(new TaskHaveCreatedEvent($m, []));

        return $m;
    }

    public function edit($status, $name, $text, $town_id, $type_id, $project_id, $industry_id, $complexity, $specialization_id, $date_end, $points_win, $points_participant, $privilege, $privilege_description, $authored_visible, $tu_count)
    {
        $this->status = $status;
        $this->name = $name;
        $this->text = $text;
        $this->town_id = $town_id;
        $this->type_id = $type_id;
        $this->project_id = $project_id;
        $this->industry_id = $industry_id;
        $this->complexity = $complexity;
        $this->specialization_id = $specialization_id;
        $this->date_end = $date_end;
        $this->points_win = $points_win;
        $this->points_participant = $points_participant;
        $this->privilege = $privilege;
        $this->privilege_description = $privilege_description;
        $this->tu_count = $tu_count;
        $this->authored_visible = $authored_visible;

        $this->recordEvent(new TaskHaveUpdatedEvent($this, []));
    }

    public function setStatus(string $status)
    {
        $this->status = $status;

        $this->recordEvent(new TaskStatusHaveChangedEvent($this, []));
    }

    public function isTeam()
    {
        return $this->type_id === 'team';
    }

    public function isParticipant()
    {
        return !empty(TaskParticipant::findOne(['task_id' => $this->id, 'participant_id' => \Yii::$app->getUser()->getId()]));

    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\components\AccessController;
use common\models\User;
use yii2tech\balance\ManagerDb;

class SiteController extends AccessController
{
  public function actionMoney()
  {
//    $id  = \Yii::$app->getUser()->getId(); //47
//    \Yii::$app->balanceManager->increase(1, 500, ['extra' => 'custom']);
//    \common\components\VarDumper::dump($asd); exit;
    \Yii::$app->cakeBalanceManager->increase( ['userId' => 65], $event->task->count_tu );

//    $manager = \Yii::$app->balanceManager;
//    $manager->accountBalanceAttribute = 'aiur';
//    $manager->decrease(['userId' => 7], 10);
//    echo $manager->calculateBalance(7);
//    echo \Yii::$app->balanceManager->calculateBalance(2);


    /*        echo \Yii::$app->balanceManager->calculateBalance(1);
            echo "<br>";
        echo \Yii::$app->balanceManager->calculateBalance(2);*/
//    $manager->revert(24,);
  }

  public function actionIndex()
  {
    $sql = "SELECT IF(COUNT(ip) = 0, 1, COUNT(ip)) as hits, IF(COUNT(DISTINCT ip) = 0, 1, COUNT(DISTINCT ip)) as hosts FROM stats WHERE DATE(date) = DATE(NOW())";
    $res = \Yii::$app->db->createCommand($sql)->queryOne();

    /*
     * WIDGET "Базы данных"
     */
    $sql = "SELECT table_schema 'name',  Round(Sum(data_length + index_length) / 1024 / 1024, 1) 'size'
            FROM   information_schema.tables
            GROUP  BY table_schema";
    $resDBInfo = \Yii::$app->db->createCommand($sql)->queryAll();

    $usersQt = User::find()->count();
    $usersBanned = User::find()->where(['banned' => 1])->count();
    $usersAdmins = User::find()->where(['root' => 1])->count();

    return $this->render( 'index', [
      'hits' => $res['hits'],
      'hosts' => $res['hosts'],
      'resDBInfo' => $resDBInfo,
      'usersQt' => $usersQt,
      'usersBanned' => $usersBanned,
      'usersAdmins' => $usersAdmins,
    ]);
  }

  public function actionGetStats()
  {
    $sql = 'SELECT TIME_FORMAT(t.time,"%H:%i") as hour, COUNT(s.ip) as hits, COUNT(DISTINCT s.ip) as hosts
        FROM times as t
        LEFT JOIN
          stats as s
        ON HOUR(t.time) = HOUR(s.date) AND DATE(s.date) = DATE(NOW())
        WHERE HOUR(t.time) <= HOUR(NOW())
        GROUP BY t.time
        ORDER BY t.time';

    $results = \Yii::$app->db->createCommand($sql)->queryAll();

    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    return $results;
  }

  public function actionChangeLog()
  {
    return $this->render('versions');
  }

  public function actionAuthInit()
  {
    $auth = \Yii::$app->authManager;
//    $role = $auth->getRole('moderator');

//    $permission = $auth->getPermission('')

//    $auth->assign($role, 2);
//    \common\components\VarDumper::dump($auth->getRole('admin'));
/*
    $admin = $auth->createRole('admin');
    $admin->description = 'Администратор';
    $auth->add($admin);

    $moderator = $auth->createRole('moderator');
    $moderator->description = 'Модератор';
    $auth->add($moderator);

    $customer = $auth->createRole('customer');
    $customer->description = 'Заказчик';
    $auth->add($customer);

    $provider = $auth->createRole('provider');
    $provider->description = 'Исполнитель';
    $auth->add($provider);

    $manageUsers = $auth->createPermission('manageUsers');
    $manageUsers->description = 'Manage users';
    $auth->add($manageUsers);*/

    $visitAdminPanel = $auth->createPermission('visitAdminPanel');
    $visitAdminPanel->description = 'Админ панель';
    $auth->add($visitAdminPanel);

    $admin = $auth->getRole('admin');
    $auth->addChild($admin, $visitAdminPanel);

//    $admin = $auth->getRole('admin');
//    $auth->addChild($admin, $visitAdminPanel);

//    \Yii::$app->authManager->removeAll();
  }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use aiur\forms\LostPasswordForm;
use aiur\forms\ResetPasswordForm;
use aiur\services\LostPasswordService;
use common\models\Industry;
use common\models\MainReview;
use common\models\Task;
use frontend\components\FrontendController;
use yii\helpers\ArrayHelper;

class SiteController extends FrontendController
{
    public $enableCsrfValidation = false;

    private $lostPasswordService;

    public function __construct( $id, $module, LostPasswordService $lostPasswordService, array $config = [] )
    {
        parent::__construct( $id, $module, $config );

        $this->lostPasswordService = $lostPasswordService;
    }


  public function actionIndex()
  {
    $mainReviews = MainReview::find()->all();
    $countTasks = Task::find()->where(['status' => 'published'])->count();
    $lasTasks = Task::find()->where(['status' => 'published'])->orderBy('date_add DESC')->limit(5)->all();
    $countCategories = Industry::find()->where(['id' => ArrayHelper::getColumn($lasTasks, 'industry_id')])->count();

    return $this->render('index',[
      'user' => \Yii::$app->getUser()->getIdentity(),
      'countTasks' => $countTasks,
      'countCategories' => $countCategories,
      'lasTasks' => $lasTasks,
      'mainReviews' => $mainReviews,
    ]);
  }

    public function actionError()
    {
        $exception = \Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
        return false;
    }

    public function actionLostPassword()
    {
        $form = new LostPasswordForm();
        if($form->load(\Yii::$app->request->post(), 'fd') && $form->validate())
        {
            $this->lostPasswordService->request($form);
            return true;
        }

        return false;
    }

    public function actionResetPassword($token)
    {
        $this->lostPasswordService->validate($token);

        $form = new ResetPasswordForm();

        if($form->load(\Yii::$app->request->post(), 'fd') && $form->validate())
        {
            $this->lostPasswordService->reset($token, $form);

            return $this->goHome();
        }

        return $this->render('reset-password');
    }
}

frontend/views/site/error.php
<?php
$this->title = $exception->getMessage();
?>
<?php if ($exception->statusCode == 404):?>
<main class="t-page_text">
    <div class="t-error-page"><img src="/img/no_img.png">
        <h1>404</h1>
        <h2>Страница не найдена</h2>
        <p>Возможно страница была удалена — такое бывает.<br>Можно перейти на главную.</p>
    </div>
</main>
<?php else:;?>
    <main class="t-page_text">
        <div class="t-error-page"><img src="/img/no_img.png">
            <h1><?=$exception->statusCode?></h1>
            <h2><?=$exception->getName()?></h2>
            <p><?=$exception->getMessage()?></p>
        </div>
    </main>
<?php endif;?>

frontend/views/site/index.php
<?php
$this->title = 'Главная страница';
?>

<main data-theme="yeallow-white" class="t-page_home">
  <section class="t-preview">
    <div class="t-stuck_img"></div>
    <h1>Treeup — это сервис по построению команды с решением задач на основе краудсорсинга</h1>
    <?if(\Yii::$app->user->getIsGuest()):?>
      <div class="t-create-get-task flip-container">
        <div data-type="flip" class="tabs only-mobyle"><a href="#advantage_client" class="active">Для заказчика</a><i></i><a href="#advantage_developer">Для исполнителя</a></div>
        <ul>
          <li>
            <h2>Для заказчика</h2>
            <p>Лучшие исполнители с гарантией выполнения работы</p><a href="#create-task" class="t-btn js-link_auth">Создать задачу</a>
          </li>
          <li>
            <h2>Для исполнителя</h2>
            <p>Получай заказы с гарантией оплаты от лучших заказчиков</p><a href="#get-task" class="t-btn js-link_auth">Предложить решение</a>
          </li>
        </ul>
      </div>
    <?else:?>
      <?if($user->typeProfileIs('customer')):?>
          <div class="t-create-get-task t-create-get-task_buttons">
            <a href="/tasks/add" class="t-btn">Создать задачу</a>
            <a href="/profile/customer/feed" class="t-btn t-btn_border t-btn_white">Личный кабинет</a>
          </div>
        <?else:?>
          <div class="t-create-get-task t-create-get-task_buttons">
            <a href="/tasks" class="t-btn">Приступить к работе</a>
            <a href="/profile/business/feed" class="t-btn t-btn_border t-btn_white">Личный кабинет</a>
          </div>
        <?endif;?>
    <?endif;?>

    <div class="t-new-task">
      <h2>Новые задачи <span><?=\Yii::t('app', '{n,plural, one{# задача} few{# задачи} many{# задач} other{# задач}}', ['n' => $countTasks])?> в <?=\Yii::t('app', '{n,plural, one{# категории} few{# категориях} many{# категориях} other{# категориях}}', ['n' => $countCategories])?> </span></h2>
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <?foreach($lasTasks as $lastTask):?>
            <div class="swiper-slide">
              <a href="/tasks/<?=$lastTask->id?>/view" class="t-task-item">
                <div class="t-task-item__background"></div>
                <div class="t-task-item__img">
                  <span>2</span>
                  <img src="<?=\aiur\helpers\user\LogoHelper::getUserLogoUrl($lastTask->creator)?>">
                </div>
                <div class="t-task-item__info">
                  <div class="price">
                    <?if(!$lastTask->isTeam() && $lastTask->tu_count):?>
                      <img src="/img/bonus1.png"><span><?=$lastTask->tu_count?></span>
                    <?endif;?>
                    <img src="/img/bonus2.png"><span><?=$lastTask->points_win?><?if(!$lastTask->isTeam() && $lastTask->points_participant):?>/<?endif;?><?=$lastTask->points_participant?></span>
                  </div>
                  <div class="level level_<?=$lastTask->complexity?>"><span></span><span></span><span></span></div>
                  <div class="name"><?=\aiur\helpers\user\UserHelper::getUserName($lastTask->creator)?></div>
                  <div class="description"><?=$lastTask->name?></div>
                  <hr>
                  <ul class="base-info">
                    <li><?=$lastTask->date_end?></li>
                    <?if(isset($lastTask->industry)):?>
                      <li><?=$lastTask->industry->name?></li>
                    <?endif;?>
                    <li><?=$lastTask->town->name??''?></li>
                  </ul>
                </div>
              </a>
            </div>
          <?endforeach;?>
        </div>
        <div class="swiper-pagination"></div>
      </div><a href="/tasks" class="t-btn">Посмотреть все</a>
    </div>
  </section>

  <?=\frontend\widgets\Advantages::widget()?>

  <?=\frontend\widgets\HowToWork::widget()?>

  <section class="t-reviews">
    <h2>Отзывы о нас</h2>
    <div class="swiper-container t-reviews-slider">
      <div class="swiper-pagination"></div>
      <div class="swiper-wrapper">
        <?foreach($mainReviews as $review):?>
          <div class="swiper-slide t-reviews-slider__item"><img src="<?=$review->getImageFileUrl('image')?>">
            <div class="prof"><?=$review->name?></div>
            <div class="text"><?=$review->text?></div>
            <?if(filter_var($review->link, FILTER_VALIDATE_URL)):?>
              <a href="<?=$review->link?>" target="_blank"><?=$review->link?></a>
            <?else:?>
              <a href="http://<?=$review->link?>" target="_blank"><?=$review->link?></a>
            <?endif;?>
          </div>
        <?endforeach;?>
      </div>
    </div>
  </section>
</main>

frontend/views/site/reset-password.php
<?php
$this->title = 'Сброс пароля';
?>

<main class="t-page_text">
  <h1>Сброс пароля</h1>
  <div class="t-work-area">
    <form id="create_password" action="<?=\Yii::$app->request->url?>" method="POST" class="js-create_password">
        <div class="t-input"><span>Новый пароль</span>
            <input type="password" name="fd[password]" data-name="password_doubel" class="identical">
        </div>
        <div class="t-input"><span>Повторите новый пароль</span>
            <input type="password" name="fd[password_repeat]" data-name="password_doubel" class="identical">
        </div>
        <button disabled class="t-btn">Сохранить</button>
    </form>
  </div>
</main>